<?php

namespace Tigreboite\FunkylabBundle\Generator;

use Tigreboite\FunkylabBundle\Generator\Field\Field;

class DatagridFormater extends Formater {

    protected $type = "Datagrid";

    public function getViews()
    {
        $sName          = array();
        $TRName         = array();
        $EditableFields = array();
        $EditableJS     = array();

        foreach($this->getFields() as $field)
        {
            if($field['visible'])
            {
                $TRName[]="<th>".$field['name']."</th>";
                $sName[]='{ "sName": "'.$field['varname'].'" }';

            }
            if($field['editable'])
            {
                $OBjField = new Field($field['dataType'],$field['name'],$field['varname'],array('path'=>"admin_".strtolower($this->entityName)));
                $EditableFields[]=$OBjField->getHTML();
                $EditableJS[]=$OBjField->getJS();
            }
        }

        $files = array();
        $path = dirname(__FILE__)."/Resources/views/".$this->type;
        foreach (glob($path."/*.twig") as $filename) {
            $body ="{# Generated by Tigreboite\\FunkylabBundle ".date("Y-m-d h:i:s")." #}\n";
            $body.=file_get_contents($filename);

            $body = str_replace('%datagrid_entity_path%',"admin_".strtolower($this->entityName),$body);
            $body = str_replace('%datagrid_entity_name%',UCFirst(strtolower($this->entityName)),$body);
            $body = str_replace('%sname_fields%',implode(',',$sName),$body);
            $body = str_replace('%datagrid_entity_fields%',implode('',$TRName),$body);
            $body = str_replace('%sname_fields%',implode(',',$sName),$body);
            $body = str_replace('%editable_fields%',implode("\n",$EditableFields),$body);
            $body = str_replace('%javascript%',implode("\n",$EditableJS),$body);

            $files[basename($filename)]=$body;
        }
        return $files;
    }

}
