<?php

namespace Tigreboite\FunkylabBundle\Generator;

use Doctrine\Common\Annotations\Reader;
use Doctrine\Common\Annotations\AnnotationReader;
use Tigreboite\FunkylabBundle\Generator\Field\Fields;

abstract class Formater {

    protected $bundle;
    protected $entity;
    protected $type;
    protected $classController;

    public function __construct($bundle,$entity)
    {
        $this->bundle          = $bundle;
        $this->entity          = $entity;
        $this->entityName      = explode('\\',$entity);
        $this->entityName      = end($this->entityName);
        $this->annotations     = $this->processAnnotation();
        $this->classController = 'Tigreboite\\FunkylabBundle\\Generator\\Controller\\'.$this->type.'Controller';
    }

    public function getController()
    {
        $code = file_get_contents(dirname(__FILE__)."/Controller/".$this->type."Controller.php");

        $repoBundle = explode('\\',$this->entity);
        unset($repoBundle[count($repoBundle)-1]);
        unset($repoBundle[count($repoBundle)-1]);
        $repoBundle = implode('',$repoBundle);

        $code = str_replace('Tigreboite\FunkylabBundle\Form\DatagridType',$this->bundle.'\\Form\\'.$this->entityName."Type",$code);
        $code = str_replace('Tigreboite\FunkylabBundle\Entity\Datagrid',$this->bundle.'\\Entity\\'.$this->entityName,$code);
        $code = str_replace('TigreboiteFunkylabBundle',$repoBundle,$code);
        $code = str_replace('Tigreboite\FunkylabBundle\Generator',$this->bundle,$code);
        $code = str_replace('_'.strtolower($this->type),"_".strtolower($this->entityName),$code);
        $code = str_replace('/admin/'.strtolower($this->type),"/admin/".strtolower($this->entityName),$code);
        $code = str_replace('%entity_name%',$this->entityName,$code);
        $code = str_replace('%class_name%',strtolower($this->entityName),$code);
        $code = str_replace('%bundle_name%',$this->bundle,$code);
        $code = str_replace('%security_roles%','@Security("has_role(\'ROLE_SUPER_ADMIN\')")',$code);
        $code = str_replace($this->type,$this->entityName,$code);

        return $code;
    }

    public function getFormType()
    {
        $code = file_get_contents(dirname(__FILE__)."/Form/DataType.php");
        $code = str_replace('%entity_name%',UCFirst(strtolower($this->entityName)),$code);
        $code = str_replace('%bundle_name%',$this->bundle,$code);
        $code = str_replace('%bundle_name_entity_name%',strtolower($this->bundle."_".$this->entityName),$code);
        $code = str_replace('DataType',UCFirst(strtolower($this->entityName))."Type",$code);
        $code = str_replace('Tigreboite\FunkylabBundle\Generator',$this->bundle,$code);

        $fields="";
        foreach($this->getFields() as $field)
        {
            if($field['editable'])
            {
                $fields.="\$builder->add('".$field['varname']."');\n";
            }
        }

        $code = str_replace('$builder->add("");',$fields,$code);

        return $code;
    }

    public function getViews()
    {
        $sName          = array();
        $TRName         = array();
        $EditableFields = array();

        foreach($this->getFields() as $field)
        {
            if($field['visible'])
            {
                $TRName[]="<th>".$field['name']."</th>";
                $sName[]='{ "sName": "'.$field['varname'].'" }';

            }
            if($field['editable'])
            {
                $OBjField = new Fields($field['dataType'],$field['name'],$field['varname']);
                $EditableFields[]=$OBjField->getHTML();
            }
        }

        $files = array();
        $path = dirname(__FILE__)."/Resources/views/".$this->type;
        foreach (glob($path."/*.twig") as $filename) {
            $body ="{# Generated by Tigreboite\\FunkylabBundle ".date("Y-m-d h:i:s")." #}\n";
            $body.=file_get_contents($filename);

            $body = str_replace('%datagrid_entity_path%',"admin_".strtolower($this->entityName),$body);
            $body = str_replace('%datagrid_entity_name%',UCFirst(strtolower($this->entityName)),$body);
            $body = str_replace('%sname_fields%',implode(',',$sName),$body);
            $body = str_replace('%datagrid_entity_fields%',implode('',$TRName),$body);
            $body = str_replace('%sname_fields%',implode(',',$sName),$body);
            $body = str_replace('%editable_fields%',implode("\n",$EditableFields),$body);

            $files[basename($filename)]=$body;
        }
        return $files;
    }

    private function getFields()
    {
        $fields = array();
        foreach($this->annotations['variables_annotations'] as $k=>$annotations)
        {
            $field = array(
              'name'        => '',
              'fieldname'   => '',
              'type'        => '',
              'editable'    => true,
              'visible'     => true,
              'sortable'    => false,
              'dataType'    => '',
              'searchable'  => false,
            );

            foreach($annotations as $annotation)
            {
                if(get_class($annotation)=="Tigreboite\\FunkylabBundle\\Annotation\\Crud")
                {
                    $field['name']       = $annotation->getPropertyName();
                    $field['visible']    = $annotation->getVisible();
                    $field['sortable']   = $annotation->getSortable();
                    $field['editable']   = $annotation->getEditable();
                    $field['searchable'] = $annotation->getSearchable();
                    $field['dataType']   = $annotation->getDataType();
                }
                if(get_class($annotation)=="Doctrine\\ORM\\Mapping\\Column")
                {
                    $field['varname']   = $this->annotations['variables'][$k]->name;
                    $field['fieldname'] = $annotation->name;
                    $field['type']      = $annotation->type;
                }

                if(get_class($annotation)=="Doctrine\\ORM\\Mapping\\GeneratedValue")
                {
                    $field['generatedValue'] = true;
                }
            }

            if($field['name']=="")
            {
                $field['name'] = $field['fieldname'];
            }
            if(isset($field['generatedValue']))
            {
                $field['editable'] = false;
            }
            $fields[] = $field;
        }

        return $fields;
    }

    private function processAnnotation()
    {
        $annotations = array(
            'variables'             => array(),
            'variables_annotations' => array(),
            'methodes'              => array(),
            'methodes_annotations'  => array(),
        );

        $annotationReader = new AnnotationReader();
        $reflectionClass = new \ReflectionClass($this->entity);

        // Class Annotations
        $classAnnotations = $annotationReader->getClassAnnotations($reflectionClass);

        // fields Annotations
        foreach($reflectionClass->getProperties() as $reflectionProperty)
        {
            $variable = new \ReflectionProperty($this->entity, $reflectionProperty->getName());
            if(!empty($variable))
                $annotations['variables'][]=$variable;
            $variable_annotations = $annotationReader->getPropertyAnnotations($variable);
            if(!empty($variable_annotations))
                $annotations['variables_annotations'][]=$variable_annotations;
        }

        // Methods Annotations
        foreach($reflectionClass->getMethods() as $reflectionMethod)
        {
            $method = new \ReflectionMethod($this->entity, $reflectionMethod->getName());
            if(!empty($method))
                $annotations['methodes'][]=$method;
            $method_annotations = $annotationReader->getMethodAnnotations($method);
            if(!empty($method_annotations))
                $annotations['methodes_annotations'][]=$method_annotations;
        }

        return $annotations;
    }

}
