<?php

namespace Tigreboite\FunkylabBundle\Generator;

use Doctrine\Common\Annotations\Reader;
use Doctrine\Common\Annotations\AnnotationReader;

abstract class Formater {

    protected $bundle;
    protected $entity;
    protected $type;
    protected $classController;

    public function __construct($bundle,$entity)
    {
        $this->bundle          = $bundle;
        $this->entity          = $entity;
        $this->entityName      = explode('\\',$entity);
        $this->entityName      = end($this->entityName);
        $this->annotations     = $this->processAnnotation();
        $this->classController = 'Tigreboite\\FunkylabBundle\\Generator\\Controller\\'.$this->type.'Controller';
    }

    public function getController()
    {
        $code = file_get_contents(dirname(__FILE__)."/Controller/".$this->type."Controller.php");

        $repoBundle = explode('\\',$this->entity);
        unset($repoBundle[count($repoBundle)-1]);
        unset($repoBundle[count($repoBundle)-1]);
        $repoBundle = implode('',$repoBundle);

        $code = str_replace('Tigreboite\FunkylabBundle\Form\DatagridType',$this->bundle.'\\Form\\'.$this->entityName."Type",$code);
        $code = str_replace('Tigreboite\FunkylabBundle\Entity\Datagrid',$this->bundle.'\\Entity\\'.$this->entityName,$code);
        $code = str_replace('TigreboiteFunkylabBundle',$repoBundle,$code);
        $code = str_replace('Tigreboite\FunkylabBundle\Generator',$this->bundle,$code);
        $code = str_replace('_'.strtolower($this->type),"_".strtolower($this->entityName),$code);
        $code = str_replace('/admin/'.strtolower($this->type),"/admin/".strtolower($this->entityName),$code);
        $code = str_replace('%entity_name%',$this->entityName,$code);
        $code = str_replace('%class_name%',strtolower($this->entityName),$code);
        $code = str_replace('%bundle_name%',$this->bundle,$code);
        $code = str_replace('%security_roles%','@Security("has_role(\'ROLE_MODERATOR\') || has_role(\'ROLE_SUPER_ADMIN\')")',$code);
        $code = str_replace($this->type,$this->entityName,$code);

        return $code;
    }

    public function getFormType()
    {
        $code = file_get_contents(dirname(__FILE__)."/Form/DataType.php");
        $code = str_replace('%entity_name%',UCFirst(strtolower($this->entityName)),$code);
        $code = str_replace('%bundle_name%',$this->bundle,$code);
        $code = str_replace('%bundle_name_entity_name%',strtolower($this->bundle."_".$this->entityName),$code);
        $code = str_replace('DataType',UCFirst(strtolower($this->entityName))."Type",$code);
        return $code;
    }

    public function getViews()
    {
        $files = array();
        $path = dirname(__FILE__)."/Resources/views/".$this->type;
        foreach (glob($path."/*.twig") as $filename) {
            $body ="{#  Generated by Funkylab #}\n";
//            $body.=$this->fixedCode(file_get_contents($filename));
            $body.=file_get_contents($filename);

            $body = str_replace('%datagrid_entity_path%',"admin_".strtolower($this->entityName),$body);
            $body = str_replace('%datagrid_entity_name%',UCFirst(strtolower($this->entityName)),$body);

            $files[basename($filename)]=$body;
        }
        return $files;
    }

    private function processAnnotation()
    {
        $annotations = array(
            'variables'             => array(),
            'variables_annotations' => array(),
            'methodes'              => array(),
            'methodes_annotations'  => array(),
        );

        $annotationReader = new AnnotationReader();
        $reflectionClass = new \ReflectionClass($this->entity);

        // Class Annotations
        $classAnnotations = $annotationReader->getClassAnnotations($reflectionClass);

        // fields Annotations
        foreach($reflectionClass->getProperties() as $reflectionProperty)
        {
            $variable = new \ReflectionProperty($this->entity, $reflectionProperty->getName());
            if(!empty($variable))
                $annotations['variables'][]=$variable;
            $variable_annotations = $annotationReader->getPropertyAnnotations($variable);
            if(!empty($variable_annotations))
                $annotations['variables_annotations'][]=$variable_annotations;
        }

        // Methods Annotations
        foreach($reflectionClass->getMethods() as $reflectionMethod)
        {
            $method = new \ReflectionMethod($this->entity, $reflectionMethod->getName());
            if(!empty($method))
                $annotations['methodes'][]=$method;
            $method_annotations = $annotationReader->getMethodAnnotations($method);
            if(!empty($method_annotations))
                $annotations['methodes_annotations'][]=$method_annotations;
        }

        return $annotations;
    }

}
