services:

    tigreboitefunkylab.listener.post_persist_listner:
        class: Tigreboite\FunkylabBundle\Listener\PostPersistListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    tigreboitefunkylab.listener.post_update_listner:
        class: Tigreboite\FunkylabBundle\Listener\PostPersistListener
        tags:
            - { name: doctrine.event_listener, event: postUpdate }

    tigreboitefunkylab.listener.post_delete_listner:
        class: Tigreboite\FunkylabBundle\Listener\PostPersistListener
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    tigreboitefunkylab.test.listener:
        class: Tigreboite\FunkylabBundle\EventListener\TestEventListener
        tags:
            - { name: kernel.event_subscriber }
