tigreboite_funkylab:
    resource: "@TigreboiteFunkylabBundle/Controller/"
    type:     annotation
    prefix:   /admin/

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_profile_show:
    path: /account

lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /admin/translator/