security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        Tigreboite\FunkylabBundle\Entity\User: sha512

    providers:
        user_db:
            entity: { class: Tigreboite\FunkylabBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:   ^/(_(profiler|wdt)|css|images|js)/
            security:  false
            anonymous: true
#            host: host

        secured_area:
            pattern:    ^/admin
            form_login:
                provider:   user_db
                check_path: funkylab_login_check
                login_path: /admin/login
                default_target_path: /
                always_use_default_target_path: false
            logout:
                path:   /admin/logout
                target: funkylab_login
            anonymous:  true

        account_area:
            pattern:    ^/
            form_login:
                provider:   user_db
                check_path: login_check
                login_path: /
                success_handler: funkylab.handler.authentication
                failure_handler: funkylab.handler.authentication
            logout:
                path:   fos_user_security_logout
                target: homepage
            anonymous:  true

    access_control:
        - { path: ^/.*/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*/register,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account,  roles: ROLE_USER }
        - { path: ^/admin/,   roles: [ROLE_RH, ROLE_ETUDE] }

    role_hierarchy:
        ROLE_ETUDE  : ROLE_USER
        ROLE_RH     : ROLE_USER
        ROLE_ADMIN  : [ROLE_ETUDE, ROLE_RH]
        ROLE_SUPER_ADMIN: ROLE_ADMIN
