security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Tigreboite\FunkylabBundle\Entity\User: sha512

    providers:
        user_db:
            entity: { class: Tigreboite\FunkylabBundle\Entity\User, property: username }

    firewalls:
        dev:
            pattern:   ^/(_(profiler|wdt)|css|images|js)/
            security:  false
            anonymous: true

        secured_area:
            pattern:    ^/
            form_login:
                provider:   user_db
                check_path: fos_user_security_check
                login_path: /
                default_target_path: /
                always_use_default_target_path: false
            logout:
                path:   fos_user_security_logout
                target: funkylab_home
            anonymous:  true

    access_control:
        - { path: ^/.*/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/account, role: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
