services:
    # the menu builder service. Can be used for several menus
    tigreboitefunkylab.menu_builder:
        class: Tigreboite\FunkylabBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    # Main Menu
    tigreboitefunkylab.menu.main_menu:
        class: Knp\Menu\MenuItem
        factory: ["@tigreboitefunkylab.menu_builder", createMainMenu]
        arguments:
          - "@request_stack"
          - "@annotation_reader"
          - "@service_container"
        tags:
            - { name: knp_menu.menu, alias: main_menu }

    # Breadcrumb
    tigreboitefunkylab.menu.breadcrumb:
        class: Knp\Menu\MenuItem
        factory: ["@tigreboitefunkylab.menu_builder",createBreadcrumbMenu]
        arguments:
          - "@request_stack"
          - "@annotation_reader"
          - "@service_container"
        tags:
            - { name: knp_menu.menu, alias: breadcrumb }

    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default, priority: 1 }
        calls:
            - [ setAnnotationReader, ["@annotation_reader" ] ]

    tigreboitefunkylab.file_name_generator:
        class: Tigreboite\FunkylabBundle\Service\UniqueFileNameGeneratorService
        arguments:
            - "@cocur_slugify"
    funkylab.service:
        class: Tigreboite\FunkylabBundle\Service\FunkylabService
        arguments: ["@session"]

    funkylab.collector:
        class: Tigreboite\FunkylabBundle\DataCollector\FunkylabCollector
        arguments: ["@funkylab.service"]
        public: false
        tags:
            - { name: data_collector, id: funkylab.collector, template: TigreboiteFunkylabBundle:Collector:funkylab }

    funkylab.factory.bloc:
        class: Tigreboite\FunkylabBundle\Factory\BlocFactory
        arguments: ["@funkylab.manager.actuality","@funkylab.manager.page"]

    funkylab.handler.authentication:
        class: Tigreboite\FunkylabBundle\Handler\AuthenticationHandler
        arguments: ["@translator"]
